import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "./context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ermakovich",
  description: "Generated by Kirill Ermakovich",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className=" mx-auto p-4">
            <Navbar />
            <div className="mt-8">{children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
